export type PackageCategory =
  | 'UI Components'
  | 'Theming & Design'
  | 'Markdown & Docs'
  | 'CLI Tools'
  | 'Shared Libraries'

export interface PackageMeta {
  slug: string
  name: string
  version: string
  description: string
  category: PackageCategory
  npmUrl: string
  githubUrl: string
  demoUrl?: string
  keywords: string[]
  install: string
}

export interface CategoryDef {
  id: PackageCategory
  label: string
  icon: string
  color: string
}

export const CATEGORIES: CategoryDef[] = [
  { id: 'UI Components',    label: 'UI Components',    icon: '🧩', color: 'blue'   },
  { id: 'Theming & Design', label: 'Theming & Design', icon: '🎨', color: 'purple' },
  { id: 'Markdown & Docs',  label: 'Markdown & Docs',  icon: '📝', color: 'green'  },
  { id: 'CLI Tools',        label: 'CLI Tools',        icon: '⚙️',  color: 'yellow' },
  { id: 'Shared Libraries', label: 'Shared Libraries', icon: '📦', color: 'slate'  },
]

export const PACKAGES: PackageMeta[] = [
  // ─── UI Components ───────────────────────────────────────────────────
  {
    slug: 'dd-menu',
    name: '@asafarim/dd-menu',
    version: '1.5.0',
    description: 'A minimal, elegant dropdown menu React component with recursive nesting, multiple themes, custom triggers, keyboard navigation, and accessibility support.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/dd-menu',
    githubUrl: 'https://github.com/AliSafari-IT/dd-menu',
    demoUrl: 'https://alisafari-it.github.io/dd-menu/',
    keywords: ['dropdown', 'menu', 'recursive', 'typescript'],
    install: 'pnpm add @asafarim/dd-menu',
  },
  {
    slug: 'toast',
    name: '@asafarim/toast',
    version: '1.2.0',
    description: 'React toast notification system for ASafariM frontends.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/toast',
    githubUrl: 'https://github.com/AliSafari-IT/toast',
    demoUrl: 'https://alisafari-it.github.io/toast/',
    keywords: ['toast', 'notification', 'alert', 'react'],
    install: 'pnpm add @asafarim/toast',
  },
  {
    slug: 'progress-bars',
    name: '@asafarim/progress-bars',
    version: '1.3.0',
    description: 'Responsive, customisable React progress bar components built on top of ASafariM design tokens.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/progress-bars',
    githubUrl: 'https://github.com/alisafari-it/progress-bars',
    demoUrl: 'https://alisafari-it.github.io/progress-bars',
    keywords: ['progress', 'bar', 'loading', 'react'],
    install: 'pnpm add @asafarim/progress-bars',
  },
  {
    slug: 'changelog-timeline',
    name: '@asafarim/changelog-timeline',
    version: '0.6.0',
    description: 'Responsive, paginated vertical changelog timeline using ASafariM design tokens.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/changelog-timeline',
    githubUrl: 'https://github.com/AliSafari-IT/changelog-timeline',
    demoUrl: 'https://alisafari-it.github.io/changelog-timeline/',
    keywords: ['changelog', 'timeline', 'history', 'react'],
    install: 'pnpm add @asafarim/changelog-timeline',
  },
  {
    slug: 'navigation',
    name: '@asafarim/navigation',
    version: '0.2.3',
    description: 'Reusable, framework-agnostic React navigation components (navbar, sidebar, drawer, dropdown) for ASafariM apps and beyond.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/navigation',
    githubUrl: 'https://github.com/alisafari-it/navigation',
    demoUrl: 'https://alisafari-it.github.io/navigation',
    keywords: ['navigation', 'navbar', 'sidebar', 'drawer', 'dropdown'],
    install: 'pnpm add @asafarim/navigation',
  },
  {
    slug: 'sidebar',
    name: '@asafarim/sidebar',
    version: '1.2.0',
    description: 'A collapsible sidebar component for React applications.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/sidebar',
    githubUrl: 'https://github.com/AliSafari-IT/sidebar',
    demoUrl: 'https://alisafari-it.github.io/sidebar',
    keywords: ['sidebar', 'navigation', 'collapsible', 'react'],
    install: 'pnpm add @asafarim/sidebar',
  },
  {
    slug: 'react-dropdowns',
    name: '@asafarim/react-dropdowns',
    version: '1.8.0',
    description: 'Comprehensive reusable dropdown components for React with TypeScript and mobile-first design.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/react-dropdowns',
    githubUrl: 'https://github.com/AliSafari-IT/react-dropdowns',
    demoUrl: 'https://alisafari-it.github.io/react-dropdowns/',
    keywords: ['dropdown', 'select', 'mobile-first', 'react'],
    install: 'pnpm add @asafarim/react-dropdowns',
  },
  {
    slug: 'country-language-selector',
    name: '@asafarim/country-language-selector',
    version: '0.5.2',
    description: 'A modern, accessible, reusable React + TypeScript country & language selector for navbars.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/country-language-selector',
    githubUrl: 'https://github.com/alisafari-it/country-language-switch',
    demoUrl: 'https://alisafari-it.github.io/country-language-switch/',
    keywords: ['country', 'language', 'selector', 'i18n', 'react'],
    install: 'pnpm add @asafarim/country-language-selector',
  },
  {
    slug: 'booking-calendar',
    name: '@asafarim/booking-calendar',
    version: '0.4.1',
    description: 'Google Calendar-style booking UI for scheduling and appointment management.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/booking-calendar',
    githubUrl: 'https://github.com/AliSafari-IT/booking-calendar',
    demoUrl: 'https://alisafari-it.github.io/booking-calendar',
    keywords: ['calendar', 'booking', 'scheduler', 'react'],
    install: 'pnpm add @asafarim/booking-calendar',
  },
  {
    slug: 'project-card',
    name: '@asafarim/project-card',
    version: '1.5.0',
    description: 'A React component for displaying project cards with title, image, description, tech stack, and links.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/project-card',
    githubUrl: 'https://github.com/AliSafari-IT/project-card',
    demoUrl: 'https://alisafari-it.github.io/project-card',
    keywords: ['project', 'card', 'portfolio', 'showcase', 'react'],
    install: 'pnpm add @asafarim/project-card',
  },
  {
    slug: 'paginated-project-grid',
    name: '@asafarim/paginated-project-grid',
    version: '1.5.1',
    description: 'A responsive React component for displaying paginated project cards with built-in search functionality.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/paginated-project-grid',
    githubUrl: 'https://github.com/AliSafari-IT/paginated-project-grid',
    demoUrl: 'https://alisafari-it.github.io/paginated-project-grid',
    keywords: ['pagination', 'grid', 'search', 'project', 'react'],
    install: 'pnpm add @asafarim/paginated-project-grid',
  },
  {
    slug: 'display-code',
    name: '@asafarim/display-code',
    version: '1.1.0',
    description: 'A React component for displaying syntax-highlighted code blocks with copy functionality and theme support.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/display-code',
    githubUrl: 'https://github.com/AliSafari-IT/display-code',
    demoUrl: 'https://alisafari-it.github.io/display-code/',
    keywords: ['code', 'syntax-highlight', 'prism', 'copy', 'react'],
    install: 'pnpm add @asafarim/display-code',
  },
  {
    slug: 'password-checklist',
    name: '@asafarim/password-checklist',
    version: '1.1.0',
    description: 'A robust, fully-typed React component and headless hook to display password strength rules in real time.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/password-checklist',
    githubUrl: 'https://github.com/AliSafari-IT/password-checklist',
    demoUrl: 'https://alisafari-it.github.io/password-checklist/',
    keywords: ['password', 'validation', 'strength', 'checklist', 'react'],
    install: 'pnpm add @asafarim/password-checklist',
  },
  {
    slug: 'react-privacy-consent',
    name: '@asafarim/react-privacy-consent',
    version: '1.7.2',
    description: 'A comprehensive React TypeScript package for GDPR/CCPA privacy consent management with customizable UI components.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/react-privacy-consent',
    githubUrl: 'https://github.com/AliSafari-IT/react-privacy-consent',
    demoUrl: 'https://alisafari-it.github.io/react-privacy-consent/',
    keywords: ['gdpr', 'ccpa', 'cookie', 'consent', 'privacy', 'react'],
    install: 'pnpm add @asafarim/react-privacy-consent',
  },
  {
    slug: 'navlinks',
    name: 'asafarim-navlinks',
    version: '3.4.0',
    description: 'A versatile React navigation component with unlimited multi-level dropdowns, four alignment options, mobile responsiveness, and customizable styling.',
    category: 'UI Components',
    npmUrl: 'https://www.npmjs.com/package/asafarim-navlinks',
    githubUrl: 'https://github.com/AliSafari-IT/asafarim-navlinks',
    keywords: ['navlinks', 'navigation', 'hamburger', 'dropdown', 'mobile', 'react'],
    install: 'pnpm add asafarim-navlinks',
  },

  // ─── Theming & Design ─────────────────────────────────────────────────
  {
    slug: 'design-tokens',
    name: '@asafarim/design-tokens',
    version: '0.5.0',
    description: 'ASafariM design tokens (CSS variables) with multi-theme support and 30 variable fonts (100-900).',
    category: 'Theming & Design',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/design-tokens',
    githubUrl: 'https://github.com/AliSafari-IT/design-tokens',
    demoUrl: 'https://alisafari-it.github.io/design-tokens/',
    keywords: ['design-tokens', 'css-variables', 'theming', 'fonts'],
    install: 'pnpm add @asafarim/design-tokens',
  },
  {
    slug: 'react-themes',
    name: '@asafarim/react-themes',
    version: '1.9.0',
    description: 'A comprehensive theme management system for React applications with automatic dark/light mode detection, custom theme creation, and smooth transitions.',
    category: 'Theming & Design',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/react-themes',
    githubUrl: 'https://github.com/AliSafari-IT/react-themes',
    demoUrl: 'https://alisafari-it.github.io/react-themes/',
    keywords: ['themes', 'dark-mode', 'light-mode', 'css-variables', 'react'],
    install: 'pnpm add @asafarim/react-themes',
  },
  {
    slug: 'shared-tokens',
    name: '@asafarim/shared-tokens',
    version: '0.8.1',
    description: 'A shared design tokens package (pure CSS variables) for use across multiple projects.',
    category: 'Theming & Design',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/shared-tokens',
    githubUrl: 'https://github.com/AliSafari-IT/shared-tokens',
    keywords: ['design-tokens', 'css-variables', 'shared', 'pure-css'],
    install: 'pnpm add @asafarim/shared-tokens',
  },
  {
    slug: 'themeswitch',
    name: '@asafarim/themeswitch',
    version: '28.6.2024',
    description: 'A React package for theme switching between light and dark modes, utilizing a context provider and a switcher component.',
    category: 'Theming & Design',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/themeswitch',
    githubUrl: 'https://github.com/AliSafari-IT',
    keywords: ['theme', 'dark-mode', 'light-mode', 'context', 'react'],
    install: 'pnpm add @asafarim/themeswitch',
  },

  // ─── Markdown & Docs ──────────────────────────────────────────────────
  {
    slug: 'simple-md-viewer',
    name: '@asafarim/simple-md-viewer',
    version: '1.5.2',
    description: 'A professional markdown viewer with file tree navigation, directory content browsing, and advanced YAML front matter support.',
    category: 'Markdown & Docs',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/simple-md-viewer',
    githubUrl: 'https://github.com/alisafari-it/simple-md-viewer',
    demoUrl: 'https://alisafari-it.github.io/simple-md-viewer/#/',
    keywords: ['markdown', 'viewer', 'file-tree', 'yaml-frontmatter'],
    install: 'pnpm add @asafarim/simple-md-viewer',
  },
  {
    slug: 'complete-md-viewer',
    name: '@asafarim/complete-md-viewer',
    version: '1.1.1',
    description: 'A flexible markdown viewer with support for both standalone and integrated routing use cases.',
    category: 'Markdown & Docs',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/complete-md-viewer',
    githubUrl: 'https://github.com/alisafari-it/complete-md-viewer',
    keywords: ['markdown', 'viewer', 'routing', 'standalone', 'integrated'],
    install: 'pnpm add @asafarim/complete-md-viewer',
  },
  {
    slug: 'markdown-explorer-viewer',
    name: '@asafarim/markdown-explorer-viewer',
    version: '1.2.3',
    description: 'A reusable React component for exploring and viewing markdown files with file tree navigation.',
    category: 'Markdown & Docs',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/markdown-explorer-viewer',
    githubUrl: 'https://github.com/AliSafari-IT/asafarim-webapp',
    keywords: ['markdown', 'explorer', 'file-tree', 'documentation', 'react'],
    install: 'pnpm add @asafarim/markdown-explorer-viewer',
  },
  {
    slug: 'markdown-utils',
    name: '@asafarim/markdown-utils',
    version: '1.3.3',
    description: 'Utility functions for markdown processing, metadata extraction, and content parsing.',
    category: 'Markdown & Docs',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/markdown-utils',
    githubUrl: 'https://github.com/AliSafari-IT/markdown-utils',
    demoUrl: 'https://AliSafari-IT.github.io/markdown-utils',
    keywords: ['markdown', 'metadata', 'parser', 'content', 'typescript'],
    install: 'pnpm add @asafarim/markdown-utils',
  },
  {
    slug: 'md-file-explorer',
    name: '@asafarim/md-file-explorer',
    version: '1.0.1',
    description: 'A TypeScript package for recursively exploring markdown files and folders with lazy loading capabilities.',
    category: 'Markdown & Docs',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/md-file-explorer',
    githubUrl: 'https://github.com/AliSafari-IT/md-file-explorer',
    demoUrl: 'https://alisafari-it.github.io/md-file-explorer',
    keywords: ['markdown', 'file-explorer', 'lazy-loading', 'tree-view', 'typescript'],
    install: 'pnpm add @asafarim/md-file-explorer',
  },

  // ─── CLI Tools ────────────────────────────────────────────────────────
  {
    slug: 'envage',
    name: '@asafarim/envage',
    version: '0.4.2',
    description: 'Secure, age-based encryption/decryption for .env files across multiple environments and monorepo app folders.',
    category: 'CLI Tools',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/envage',
    githubUrl: 'https://github.com/AliSafari-IT/envage',
    demoUrl: 'https://AliSafari-IT.github.io/envage',
    keywords: ['env', 'encryption', 'age', 'dotenv', 'secrets', 'cli'],
    install: 'pnpm add -g @asafarim/envage',
  },
  {
    slug: 'direxpo',
    name: '@asafarim/direxpo',
    version: '1.8.0',
    description: 'Convert your project into a beautifully formatted Markdown file — CLI tool for directory export.',
    category: 'CLI Tools',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/direxpo',
    githubUrl: 'https://github.com/AliSafari-IT/direxpo',
    demoUrl: 'https://alisafari-it.github.io/direxpo/',
    keywords: ['directory', 'export', 'markdown', 'tree', 'cli'],
    install: 'pnpm add -g @asafarim/direxpo',
  },
  {
    slug: 'direxpo-core',
    name: '@asafarim/direxpo-core',
    version: '0.5.0',
    description: 'Pure utilities for file discovery and folder tree generation. No runtime dependencies.',
    category: 'CLI Tools',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/direxpo-core',
    githubUrl: 'https://github.com/AliSafari-IT/direxpo-core',
    demoUrl: 'https://alisafari-it.github.io/direxpo-core/',
    keywords: ['file-discovery', 'folder-tree', 'utilities'],
    install: 'pnpm add @asafarim/direxpo-core',
  },
  {
    slug: 'direxpo-server',
    name: '@asafarim/direxpo-server',
    version: '0.4.0',
    description: 'Express API wrapper for MD Exporter with tree generation capabilities.',
    category: 'CLI Tools',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/direxpo-server',
    githubUrl: 'https://github.com/AliSafari-IT/direxpo-server',
    demoUrl: 'https://alisafari-it.github.io/direxpo-server/',
    keywords: ['express', 'api', 'markdown', 'tree', 'server'],
    install: 'pnpm add @asafarim/direxpo-server',
  },
  {
    slug: 'md-exporter',
    name: '@asafarim/md-exporter',
    version: '0.2.3',
    description: 'Export files from a target folder into a single Markdown file.',
    category: 'CLI Tools',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/md-exporter',
    githubUrl: 'https://github.com/AliSafari-IT/md-exporter',
    keywords: ['markdown', 'export', 'folder', 'cli', 'cross-platform'],
    install: 'pnpm add -g @asafarim/md-exporter',
  },
  {
    slug: 'appsafe-cli',
    name: '@asafarim/appsafe-cli',
    version: '0.3.1',
    description: 'Config-driven local file and folder encryption CLI for AppSafe.',
    category: 'CLI Tools',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/appsafe-cli',
    githubUrl: 'https://github.com/AliSafari-IT/asafarim-appsafe',
    keywords: ['encryption', 'files', 'folders', 'security', 'cli'],
    install: 'pnpm add -g @asafarim/appsafe-cli',
  },

  // ─── Shared Libraries ─────────────────────────────────────────────────
  {
    slug: 'shared',
    name: '@asafarim/shared',
    version: '1.7.4',
    description: 'Shared components and utilities for ASafariM web applications.',
    category: 'Shared Libraries',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/shared',
    githubUrl: 'https://github.com/AliSafari-IT/shared',
    demoUrl: 'https://alisafari-it.github.io/shared/',
    keywords: ['shared', 'components', 'utilities', 'react'],
    install: 'pnpm add @asafarim/shared',
  },
  {
    slug: 'shared-i18n',
    name: '@asafarim/shared-i18n',
    version: '0.9.0',
    description: 'A shared i18n package for React applications (i18next-based).',
    category: 'Shared Libraries',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/shared-i18n',
    githubUrl: 'https://github.com/AliSafari-IT/shared-i18n',
    demoUrl: 'https://alisafari-it.github.io/shared-i18n',
    keywords: ['i18n', 'i18next', 'internationalization', 'localization', 'react'],
    install: 'pnpm add @asafarim/shared-i18n',
  },
  {
    slug: 'shared-logging',
    name: '@asafarim/shared-logging',
    version: '1.0.0',
    description: 'A lightweight, environment-agnostic logging utility shared across all ASafariM applications.',
    category: 'Shared Libraries',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/shared-logging',
    githubUrl: 'https://github.com/AliSafari-IT/asafarim-dot-be',
    keywords: ['logging', 'shared', 'utility', 'environment-agnostic'],
    install: 'pnpm add @asafarim/shared-logging',
  },
  {
    slug: 'appsafe',
    name: '@asafarim/appsafe',
    version: '0.3.1',
    description: 'Browser-native password-based AES-256-GCM encryption for files and data.',
    category: 'Shared Libraries',
    npmUrl: 'https://www.npmjs.com/package/@asafarim/appsafe',
    githubUrl: 'https://github.com/AliSafari-IT/asafarim-appsafe',
    demoUrl: 'https://alisafari-it.github.io/asafarim-appsafe/',
    keywords: ['encryption', 'aes-256-gcm', 'web-crypto', 'browser', 'security'],
    install: 'pnpm add @asafarim/appsafe',
  },
]

export const CATEGORY_COLORS: Record<PackageCategory, { text: string; border: string; bg: string; badge: string }> = {
  'UI Components':    { text: 'text-blue-400',   border: 'border-blue-500',   bg: 'bg-blue-500/10',   badge: 'bg-blue-500/20 text-blue-300'   },
  'Theming & Design': { text: 'text-purple-400', border: 'border-purple-500', bg: 'bg-purple-500/10', badge: 'bg-purple-500/20 text-purple-300' },
  'Markdown & Docs':  { text: 'text-green-400',  border: 'border-green-500',  bg: 'bg-green-500/10',  badge: 'bg-green-500/20 text-green-300'   },
  'CLI Tools':        { text: 'text-yellow-400', border: 'border-yellow-500', bg: 'bg-yellow-500/10', badge: 'bg-yellow-500/20 text-yellow-300' },
  'Shared Libraries': { text: 'text-slate-400',  border: 'border-slate-500',  bg: 'bg-slate-500/10',  badge: 'bg-slate-500/20 text-slate-300'   },
}
