name: asafarim-devtools

services:
  devtools:
    build: .
    container_name: asafarim-devtools
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - asafarim_net

networks:
  asafarim_net:
    external: true
    name: asafarim-com_asafarim_net
